name: Blacksmith
version: ${project.version}
main: asudev.blacksmith.Blacksmith
api-version: 1.13
authors: [AsuDev]
description: Blacksmith store for dots.
commands:
  blacksmith:
    description: Blacksmith related things.
    aliases: [bsmith]
